[package]
name = "niri-config"
version.workspace = true
description = "Config types for Umbra"
authors.workspace = true
license.workspace = true
edition = "2021"
repository.workspace = true

[dependencies]
bitflags.workspace = true
csscolorparser = "0.8.3"
knuffel = "3.2.0"
miette = { version = "5.10.0", features = ["fancy-no-backtrace"] }
niri-ipc = { path = "../niri-ipc" }
regex = "1.13.1"
smithay = { workspace = true, features = ["backend_libinput"] }
tracing.workspace = true
tracy-client.workspace = true

[dev-dependencies]
insta.workspace = true
pretty_assertions = "1.4.1"
diff = "0.1.13"
